# AR数据文件路径，支持到文件夹的上层目录
# AR data file path, support to the upper directory of the folder
path:
- k:/

# miner名称，不填使用电脑名
# miner name, use the computer name without filling in
minerName:"asad"

# 在 https://www.hpool.in/center/configuration 找ApiKey
# Find ApiKey at https://www.hpool.in/center/configuration
apiKey:"areco000-b660-487b-57ce-54bb12a46318"

# 日志配置
# Log configuration
log:
  lv: info
  path: ./log/
  name: miner.log

# x-proxy配置
# x-proxy configuration
url:http://139.59.242.71:9190"	
  # 一个局域网内，代理只需要开一台就可以了，如代理所在的机器Ip是192.168.1.88，端口9190
  # 下面配置改为
  # proxy: "http://192.168.1.88:9190"
  # In a local area network, only one proxy is required. For example, the IP of the machine where the proxy is located is 192.168.1.88 and the port is 9190
  # The following configuration is changed to
  # proxy: "http://192.168.1.88:9190"
  proxy: ""

# socket 或者是http代理配置
# socket5 or http proxy
proxy:"http://139.59.242.71:9190"
    # E.g http://127.0.0.1:8888 socks5://127.0.0.1:8888
    url: ""
    username: ""
    password: ""

# 语言选择
# language selection
language: cn

# 线路
# line
line: cn

# 参数配置
# Parameter configuration
extraParams:
  # randomx 标识 largepages启用需要在电脑系统中开启Hugepage,不配置则使用默认flag
  # randomx flag Enabling largepages requires opening Hugepage in the computer system
  # largepages,hardaes,fullmem,jit,secure,argon2ssse3,argon2avx2,argon2,If not configured, use the default flag
  flags: largepages,fullmem

  # plot线程，0使用全部线程
  # plot threads, 0 use all threads
  threads: "90"

  # 禁用plot
  # disable plot
  disablePlot: false

  # 当前plot的地址，自动生成
  # The address of the current plot, automatically generated
  recordAddress: "P2zpGv_Oouw5nYeXvXE7OMKlHIM7VjnUcm-ry0iVzVA"

  # 不限制单目录容量大小，默认限制官方3.6T
  # There is no limit to the capacity of a single directory, and the official limit is 3.6T by default
  disableLimit: false

  # 启用根据partition来启动读取线程(m2等固态才需要开启，机械盘否则会读竞争，算力下降)，默认是path启动读取线程
  # Enable to start the reading thread according to the partition (solid state such as m2 needs to be turned on,
  # otherwise the mechanical disk will read competition, and the computing power will drop), the default is path to start the reading thread
  readPartition: false

  # 禁用mining，在p盘机中可以开启
  # Disable mining, it can be enabled in the p drive
  disableMining: false